version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./front-end/nginx.conf:/etc/nginx/nginx.conf
      - ./front-end:/usr/share/nginx/html
      - ./front-end/mime.types:/etc/nginx/mime.types

    restart: always
